### ISSUE TITLE
Chart editor broke after enabling some options in it

### ISSUE THREAD

**Issue by Fluffyveee** [AlanSurtaev2008/FNF-AlsuhEngine#2]
### Describe your bug here.

so as the tile says I enabled some options in the chart editor and exited out it and went back into only for it to crash 
the options I enabled are the vortex editor and the waveform for voices option

### Command Prompt/Terminal logs (if existing)

```bash
editors/ChartingState.hx (line 2576)
editors/ChartingState.hx (line 2464)
editors/ChartingState.hx (line 325)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/AlanSurtaev2008/FNF-AlsuhEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i'm using the release build 1.6.12

**Comment by AlanSurtaev2008** [comment]
It turns out that the problem is that the value of the vocals is `null`.
We'll fix it and release it soon.

**Comment by AlanSurtaev2008** [comment]
Wait 10 minutes.

**Comment by Fluffyveee** [comment]
yep it's fixed minus the version check file being a version ahead everything works fine thank you

**Comment by AlanSurtaev2008** [comment]
No problem.
